#! /usr/bin/env python

############################
## load the config

## Use the environment and the tools set in the top-level
## SConstruct file (set with 'Export') - this is very important

Import( 'env' )
myenv=env.Copy()

#############################
## The programs to build

# The sources for our program - only .ui, .skel and .cpp are accepted
sources="""
./key_cursor.c
./debug.c
./draw_barline.c
./display.c
./rests.c
./tie.c
./score.c
./splash.c
./error.c
./selection.c
./position.c
./articulation.c
./staff.c
./beam.c
./common.c
./edit.c
./draw.c
./chords.c
./file.c
./help.c
./libglade-garbage.c
./main.c
./mode.c
./notes.c
./text.c
./objects.c
./tab_transposition.c
./view.c
./score_callbacks.c
./key_event.c
./objects_callbacks.c
./mouse_event.c
./realize_area.c
./spacings.c
./insert.c
./plugin.c
"""

# Our main program
# G_program add the file to the install targets automatically,
# so you do not need to write G_install('BINDIR', '', test1, myenv)
myenv.G_program( "gscore", sources )

############################
## Customization

myenv.G_addpaths_includes('#/src/include/ #/src #/')

## Necessary libraries to link against
#myenv.KDEaddlibs( 't' )

## This shows how to add other link flags to the program
myenv.G_addflags_link('-export-dynamic')

#############################
## Data to install

## The ui.rc file and the tips go into datadir/appname/
#myenv.KDEinstall( 'KDEDATA', 'test1', 'test1ui.rc' )
#myenv.KDEinstall( 'KDEDATA', 'test1', 'tips' )

## The kcfg file is installed in a global kcfg directory
#myenv.KDEinstall( 'KDEKCFG', '', 'test1.kcfg' )

## Warning : there is a difference between the normal destop file used for the menu
##     and the servicetype desktop file, so they go in different directories
##     you will find more information in 'test3'
#myenv.KDEinstall( 'KDEMENU', 'Utilities', 'test1.desktop')

## Use this when you need to install a mimetype file
#myenv.KDEinstall( 'KDEMIME', 'application', 'x-test1.desktop' )

