Document: abcp
Title: Debian abcp Manual
Author: <insert document author here>
Abstract: This manual describes what abcp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/abcp/abcp.sgml.gz

Format: postscript
Files: /usr/share/doc/abcp/abcp.ps.gz

Format: text
Files: /usr/share/doc/abcp/abcp.text.gz

Format: HTML
Index: /usr/share/doc/abcp/html/index.html
Files: /usr/share/doc/abcp/html/*.html

  
