/* Generated by re2c 0.5 on Fri Dec 31 13:56:16 2004 */
#line 1 "abcpkey.re"

#include "abcp.h"


/*
  Key
  01234567890
  KETMabcdefg
  ||\\\_______ explicit accidentals (nNfFsS)
  |  \\_______ Mode (see table below)
  K   \_______ Tonic [A-G]  P (HP), p (Hp) Z (none)
    
  M Major          
  m Minor          
  X Mix            
  D Dor            
  P Phr            
  L Lyd            
  l Loc            
  I Ion            
  A Aeo
  E Explicit

Tonic use the following coding as notes:

n abcdefg 
f ijklmno
s qrstuvw
N ABCDEFG
F IJKLMNO
S QRSTUVW

Errors      

1= Missing Tonic
2= Unknown mode
3= 
4=
5=
6= Syntax error
        
 Clef:
 012345678901234567
 CENOTTLMMDNNnnSSss
 ||\\\ \\ \\   \________ subname length
 C  \\\ \\ \\___________ name length
     \\\ \\ \___________ stem direction  0100 ggss  00=auto; 11=none; 10=up; 01=down;
      \\\ \\____________ Middle (pitch and octave on the middle line [A-G] default B)
       \\\ \____________ Staff lines (0 .. 9)
        \\\_____________ Semitones transpose (-128 .. +127)
         \\_____________ Octave transpose 'O'=0
          \_____________ clef name + center line
                           40 none         (none)
                           4F percussion   (perc)
                           4F perc         (perc)
                           41 frenchviolin (treble1)
                           41 french       (treble1)
                           4A violin       (treble)
                           4A treble       (treble)
                           51 soprano      (alto1)
                           52 mezzosoprano (alto2)
                           5A alto         (alto)
                           54 tenor        (alto4)
                           55 baritone     (alto5)
                           6A bass         (bass)
                           65 subbass      (bass5)

                           71 doh1 (Gregorian)
                           72 doh2 
                           73 doh3
                           74 doh4
                           75 Fa1  (Gregorian)
                           76 Fa2
                           77 Fa3
                           78 Fa4
                           
                                        line
                           treble  0100 xxxx
                           alto    0101 xxxx
                           bass    0110 xxxx
                           doh     0111 0xxx
                           fa      0111 1xxx

If line is 0 the clef is invisible (i.e. "none" is "treble0").
if line is A (10) no line value has been specified

Staff lines
  The parser handles up to 9 staff lines numbered from 1
to 9, the position of the clef and/or the the "middle=" 
parameters determine the note on each line.

Stems
  
 0100 ggss  00=auto; 11=none; 10=up; 01=down;

Errors:
1= invalid note
2=
3=
4= Unrecognized token
5=
6=

*/


#line 148


#define getnum(x,s) do {char t; t=*s; x=0;\
                        if (t=='-' || t == '+') s++;\
                        while(isdigit(*s)) x=x*10+ (*s++ - '0');\
                        if (t=='-') x=-x;\
                       } while(0)
                       

#define v(x) (*v-'0')

static char *clef(char *pak, char *str,int off)
{
  int m,d;
  char *t; char c;
  int i;
  
  YYCTYPE *YYCURSOR,*YYLIMIT,*YYMARKER,*YYSTART,*YYEND;

  if (str==NULL || pak==NULL) return NULL;
  
  YYCURSOR=str;
  YYLIMIT=str;  while (*YYLIMIT) YYLIMIT++; 
  /*printf("clef: '%s'\n",YYCURSOR);*/
  
               /*012345678901234567*/
  /*setpack(pak,"CENOTTLMMDNNnnSSss");*/
  pak[0]='C';
  pak[1]='@';
  pak[9]='@';

  STATE(get_clef) {
  /* printf("\n---\n%s\n--\n",str); */
    skipspace(YYCURSOR);
    YYSTART=YYCURSOR;
    
    {
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy0;
yy1:	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 12) YYFILL(12);
	yych = *YYCURSOR;
	if(yych <= 'd'){
		if(yych <= 'D'){
			if(yych <= '+'){
				if(yych <= '\000')	goto yy20;
				if(yych <= '*')	goto yy22;
				goto yy16;
			} else {
				if(yych == '-')	goto yy17;
				if(yych <= 'C')	goto yy22;
				goto yy14;
			}
		} else {
			if(yych <= '`'){
				if(yych == 'F')	goto yy15;
				goto yy22;
			} else {
				if(yych <= 'a')	goto yy13;
				if(yych <= 'b')	goto yy12;
				if(yych >= 'd')	goto yy6;
				goto yy2;
			}
		}
	} else {
		if(yych <= 'o'){
			if(yych <= 'g'){
				if(yych <= 'e')	goto yy22;
				if(yych <= 'f')	goto yy7;
				goto yy19;
			} else {
				if(yych <= 'l')	goto yy22;
				if(yych <= 'm')	goto yy10;
				if(yych <= 'n')	goto yy4;
				goto yy18;
			}
		} else {
			if(yych <= 's'){
				if(yych <= 'p')	goto yy5;
				if(yych <= 'r')	goto yy22;
				goto yy9;
			} else {
				if(yych <= 't')	goto yy11;
				if(yych == 'v')	goto yy8;
				goto yy22;
			}
		}
	}
yy2:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'l')	goto yy219;
	goto yy3;
yy3:
#line 292
	{ while (*YYCURSOR & (!isspace(*YYCURSOR))) YYCURSOR++;
                             setperr(pak,1);
                             GOTO(get_clef); }
yy4:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 'l'){
		if(yych == 'a')	goto yy211;
		goto yy3;
	} else {
		if(yych <= 'm')	goto yy208;
		if(yych == 'o')	goto yy212;
		goto yy3;
	}
yy5:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'e')	goto yy206;
	goto yy3;
yy6:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'o')	goto yy201;
	if(yych == 'r')	goto yy202;
	goto yy3;
yy7:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'a')	goto yy61;
	if(yych == 'r')	goto yy189;
	goto yy3;
yy8:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'i')	goto yy183;
	goto yy3;
yy9:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '<'){
		if(yych <= '\r'){
			if(yych <= '\b')	goto yy3;
			if(yych <= '\n')	goto yy143;
			if(yych <= '\f')	goto yy3;
			goto yy143;
		} else {
			if(yych <= ' '){
				if(yych <= '\037')	goto yy3;
				goto yy143;
			} else {
				if(yych <= '/')	goto yy3;
				if(yych <= '9')	goto yy147;
				goto yy3;
			}
		}
	} else {
		if(yych <= 'n'){
			if(yych <= 'g'){
				if(yych <= '=')	goto yy145;
				goto yy3;
			} else {
				if(yych <= 'h')	goto yy139;
				if(yych <= 'm')	goto yy3;
				goto yy140;
			}
		} else {
			if(yych <= 's'){
				if(yych <= 'o')	goto yy149;
				goto yy3;
			} else {
				if(yych <= 't')	goto yy142;
				if(yych <= 'u')	goto yy141;
				goto yy3;
			}
		}
	}
yy10:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '='){
		if(yych <= '\r'){
			if(yych <= '\b')	goto yy3;
			if(yych <= '\n')	goto yy117;
			if(yych <= '\f')	goto yy3;
			goto yy117;
		} else {
			if(yych == ' ')	goto yy117;
			if(yych <= '<')	goto yy3;
			goto yy119;
		}
	} else {
		if(yych <= 'd'){
			if(yych <= '@')	goto yy3;
			if(yych <= 'G')	goto yy121;
			if(yych <= '`')	goto yy3;
			goto yy121;
		} else {
			if(yych <= 'g'){
				if(yych <= 'e')	goto yy124;
				goto yy121;
			} else {
				if(yych == 'i')	goto yy116;
				goto yy3;
			}
		}
	}
yy11:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= ','){
		if(yych <= '\r'){
			if(yych <= '\b')	goto yy3;
			if(yych <= '\n')	goto yy90;
			if(yych <= '\f')	goto yy3;
			goto yy90;
		} else {
			if(yych <= ' '){
				if(yych <= '\037')	goto yy3;
				goto yy90;
			} else {
				if(yych == '+')	goto yy94;
				goto yy3;
			}
		}
	} else {
		if(yych <= '='){
			if(yych <= '/'){
				if(yych <= '-')	goto yy94;
				goto yy3;
			} else {
				if(yych <= '9')	goto yy95;
				if(yych <= '<')	goto yy3;
				goto yy92;
			}
		} else {
			if(yych <= 'e'){
				if(yych <= 'd')	goto yy3;
				goto yy98;
			} else {
				if(yych == 'r')	goto yy89;
				goto yy3;
			}
		}
	}
yy12:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'a')	goto yy76;
	goto yy3;
yy13:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'l')	goto yy70;
	goto yy3;
yy14:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'o')	goto yy65;
	goto yy3;
yy15:	yych = *++YYCURSOR;
	if(yych == 'a')	goto yy61;
	goto yy3;
yy16:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '2'){
		if(yych <= '0')	goto yy3;
		if(yych <= '1')	goto yy55;
		goto yy56;
	} else {
		if(yych == '8')	goto yy53;
		goto yy3;
	}
yy17:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '2'){
		if(yych <= '0')	goto yy3;
		if(yych <= '1')	goto yy46;
		goto yy45;
	} else {
		if(yych == '8')	goto yy47;
		goto yy3;
	}
yy18:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '+'){
		if(yych <= '\r'){
			if(yych <= '\b')	goto yy3;
			if(yych <= '\n')	goto yy34;
			if(yych <= '\f')	goto yy3;
			goto yy34;
		} else {
			if(yych == ' ')	goto yy34;
			if(yych <= '*')	goto yy3;
			goto yy38;
		}
	} else {
		if(yych <= '9'){
			if(yych == '-')	goto yy38;
			if(yych <= '/')	goto yy3;
			goto yy39;
		} else {
			if(yych <= '='){
				if(yych <= '<')	goto yy3;
				goto yy36;
			} else {
				if(yych == 'c')	goto yy33;
				goto yy3;
			}
		}
	}
yy19:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 's')	goto yy23;
	goto yy3;
yy20:	yych = *++YYCURSOR;
	goto yy21;
yy21:
#line 291
	{ GOTO(done); }
yy22:	yych = *++YYCURSOR;
	goto yy3;
yy23:	yych = *++YYCURSOR;
	if(yych == 't')	goto yy25;
	goto yy24;
yy24:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 3:	goto yy194;
	case 2:	goto yy128;
	case 1:	goto yy123;
	case 0:	goto yy3;
	}
yy25:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy24;
	goto yy26;
yy26:	yych = *++YYCURSOR;
	if(yych != 'm')	goto yy24;
	goto yy27;
yy27:	yych = *++YYCURSOR;
	if(yych == 's')	goto yy29;
	goto yy30;
yy28:
#line 278
	{ if (*YYCURSOR == '\'' || *YYCURSOR == '"') YYCURSOR++;
                             pak[9]= toupper(*YYCURSOR);
                             if ((pak[9] != 'U') && (pak[9] != 'D')) pak[9]=' ';
                             while (*YYCURSOR && !isspace(*YYCURSOR)) YYCURSOR++;
                             GOTO(get_clef);
                           }
yy29:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy30;
yy30:	if(yych <= '\r'){
		if(yych <= '\b')	goto yy28;
		if(yych <= '\n')	goto yy29;
		if(yych <= '\f')	goto yy28;
		goto yy29;
	} else {
		if(yych <= ' '){
			if(yych <= '\037')	goto yy28;
			goto yy29;
		} else {
			if(yych != '=')	goto yy28;
			goto yy31;
		}
	}
yy31:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy32;
yy32:	if(yych <= '\f'){
		if(yych <= '\b')	goto yy28;
		if(yych <= '\n')	goto yy31;
		goto yy28;
	} else {
		if(yych <= '\r')	goto yy31;
		if(yych == ' ')	goto yy31;
		goto yy28;
	}
yy33:	yych = *++YYCURSOR;
	if(yych == 't')	goto yy42;
	goto yy24;
yy34:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy35;
yy35:	if(yych <= '*'){
		if(yych <= '\f'){
			if(yych <= '\b')	goto yy24;
			if(yych <= '\n')	goto yy34;
			goto yy24;
		} else {
			if(yych <= '\r')	goto yy34;
			if(yych == ' ')	goto yy34;
			goto yy24;
		}
	} else {
		if(yych <= '/'){
			if(yych == ',')	goto yy24;
			if(yych <= '-')	goto yy38;
			goto yy24;
		} else {
			if(yych <= '9')	goto yy39;
			if(yych != '=')	goto yy24;
			goto yy36;
		}
	}
yy36:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy37;
yy37:	if(yych <= ' '){
		if(yych <= '\f'){
			if(yych <= '\b')	goto yy24;
			if(yych <= '\n')	goto yy36;
			goto yy24;
		} else {
			if(yych <= '\r')	goto yy36;
			if(yych <= '\037')	goto yy24;
			goto yy36;
		}
	} else {
		if(yych <= ','){
			if(yych != '+')	goto yy24;
			goto yy38;
		} else {
			if(yych <= '-')	goto yy38;
			if(yych <= '/')	goto yy24;
			if(yych <= '9')	goto yy39;
			goto yy24;
		}
	}
yy38:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy24;
	if(yych >= ':')	goto yy24;
	goto yy39;
yy39:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy40;
yy40:	if(yych <= '/')	goto yy41;
	if(yych <= '9')	goto yy39;
	goto yy41;
yy41:
#line 231
	{ d=1; m=0;
                             YYSTART=YYCURSOR;
                             while (isdigit(*(--YYSTART))) {
                               m += (*YYSTART - '0') * d;
                               d *= 10;
                             }
                             if (m>9) m=9;
                             if (*YYSTART == '-') m = -m;
                             pak[3] = 'O'+m;
                             GOTO(get_clef);
                           }
yy42:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy24;
	goto yy43;
yy43:	yych = *++YYCURSOR;
	if(yych != 'v')	goto yy24;
	goto yy44;
yy44:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy34;
	goto yy24;
yy45:	yych = *++YYCURSOR;
	if(yych == '2')	goto yy51;
	goto yy24;
yy46:	yych = *++YYCURSOR;
	if(yych == '5')	goto yy49;
	goto yy24;
yy47:	yych = *++YYCURSOR;
	goto yy48;
yy48:
#line 226
	{ pak[3] = 'O'-1; GOTO(get_clef); }
yy49:	yych = *++YYCURSOR;
	goto yy50;
yy50:
#line 227
	{ pak[3] = 'O'-2; GOTO(get_clef); }
yy51:	yych = *++YYCURSOR;
	goto yy52;
yy52:
#line 228
	{ pak[3] = 'O'-3; GOTO(get_clef); }
yy53:	yych = *++YYCURSOR;
	goto yy54;
yy54:
#line 225
	{ pak[3] = 'O'+1; GOTO(get_clef); }
yy55:	yych = *++YYCURSOR;
	if(yych == '5')	goto yy59;
	goto yy24;
yy56:	yych = *++YYCURSOR;
	if(yych != '2')	goto yy24;
	goto yy57;
yy57:	yych = *++YYCURSOR;
	goto yy58;
yy58:
#line 223
	{ pak[3] = 'O'+3; GOTO(get_clef); }
yy59:	yych = *++YYCURSOR;
	goto yy60;
yy60:
#line 224
	{ pak[3] = 'O'+2; GOTO(get_clef); }
yy61:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy62;
	if(yych <= '9')	goto yy63;
	goto yy62;
yy62:
#line 214
	{ pak[2] = 0x7F; GOTO(get_clef); }
yy63:	yych = *++YYCURSOR;
	goto yy64;
yy64:
#line 221
	{ pak[2] = (YYCURSOR[-1] & 0x07) + 0x78; GOTO(get_clef); }
yy65:	yych = *++YYCURSOR;
	if(yych != 'h')	goto yy24;
	goto yy66;
yy66:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy67;
	if(yych <= '9')	goto yy68;
	goto yy67;
yy67:
#line 213
	{ pak[2] = 0x77; GOTO(get_clef); }
yy68:	yych = *++YYCURSOR;
	goto yy69;
yy69:
#line 220
	{ pak[2] = (YYCURSOR[-1] & 0x07) + 0x70; GOTO(get_clef); }
yy70:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy24;
	goto yy71;
yy71:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy24;
	goto yy72;
yy72:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy73;
	if(yych <= '9')	goto yy74;
	goto yy73;
yy73:
#line 211
	{ pak[2] = 0x5A; GOTO(get_clef); }
yy74:	yych = *++YYCURSOR;
	goto yy75;
yy75:
#line 217
	{ pak[2] = YYCURSOR[-1] + 0x20; GOTO(get_clef); }
yy76:	yych = *++YYCURSOR;
	if(yych <= 'q')	goto yy24;
	if(yych <= 'r')	goto yy77;
	if(yych <= 's')	goto yy78;
	goto yy24;
yy77:	yych = *++YYCURSOR;
	if(yych == 'i')	goto yy83;
	goto yy24;
yy78:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy24;
	goto yy79;
yy79:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy80;
	if(yych <= '9')	goto yy81;
	goto yy80;
yy80:
#line 212
	{ pak[2] = 0x6A; GOTO(get_clef); }
yy81:	yych = *++YYCURSOR;
	goto yy82;
yy82:
#line 218
	{ pak[2] = YYCURSOR[-1] + 0x30; GOTO(get_clef); }
yy83:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy24;
	goto yy84;
yy84:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy24;
	goto yy85;
yy85:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy24;
	goto yy86;
yy86:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy24;
	goto yy87;
yy87:	yych = *++YYCURSOR;
	goto yy88;
yy88:
#line 207
	{ pak[2] = 0x55; GOTO(get_clef); }
yy89:	yych = *++YYCURSOR;
	if(yych == 'a')	goto yy104;
	if(yych == 'e')	goto yy103;
	goto yy24;
yy90:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy91;
yy91:	if(yych <= '*'){
		if(yych <= '\f'){
			if(yych <= '\b')	goto yy24;
			if(yych <= '\n')	goto yy90;
			goto yy24;
		} else {
			if(yych <= '\r')	goto yy90;
			if(yych == ' ')	goto yy90;
			goto yy24;
		}
	} else {
		if(yych <= '/'){
			if(yych == ',')	goto yy24;
			if(yych <= '-')	goto yy94;
			goto yy24;
		} else {
			if(yych <= '9')	goto yy95;
			if(yych != '=')	goto yy24;
			goto yy92;
		}
	}
yy92:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy93;
yy93:	if(yych <= ' '){
		if(yych <= '\f'){
			if(yych <= '\b')	goto yy24;
			if(yych <= '\n')	goto yy92;
			goto yy24;
		} else {
			if(yych <= '\r')	goto yy92;
			if(yych <= '\037')	goto yy24;
			goto yy92;
		}
	} else {
		if(yych <= ','){
			if(yych != '+')	goto yy24;
			goto yy94;
		} else {
			if(yych <= '-')	goto yy94;
			if(yych <= '/')	goto yy24;
			if(yych <= '9')	goto yy95;
			goto yy24;
		}
	}
yy94:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy24;
	if(yych >= ':')	goto yy24;
	goto yy95;
yy95:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy96;
yy96:	if(yych <= '/')	goto yy97;
	if(yych <= '9')	goto yy95;
	goto yy97;
yy97:
#line 244
	{ d=1; m=0;
                             YYSTART=YYCURSOR;
                             while (isdigit(*(--YYSTART))) {
                               m += (*YYSTART - '0') * d;
                               d *= 10;
                             }
                             if (m>127) m=127;
                             if (*YYSTART == '-') m = 256-m;
                             sethex(pak+4,m);
                             GOTO(get_clef);
                           }
yy98:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy24;
	goto yy99;
yy99:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy24;
	goto yy100;
yy100:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy24;
	goto yy101;
yy101:	yych = *++YYCURSOR;
	goto yy102;
yy102:
#line 206
	{ pak[2] = 0x54; GOTO(get_clef); }
yy103:	yych = *++YYCURSOR;
	if(yych == 'b')	goto yy110;
	goto yy24;
yy104:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy24;
	goto yy105;
yy105:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy24;
	goto yy106;
yy106:	yych = *++YYCURSOR;
	if(yych != 'p')	goto yy24;
	goto yy107;
yy107:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy24;
	goto yy108;
yy108:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy24;
	goto yy109;
yy109:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy90;
	goto yy24;
yy110:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy24;
	goto yy111;
yy111:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy24;
	goto yy112;
yy112:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy113;
	if(yych <= '9')	goto yy114;
	goto yy113;
yy113:
#line 210
	{ pak[2] = 0x4A; GOTO(get_clef); }
yy114:	yych = *++YYCURSOR;
	goto yy115;
yy115:
#line 216
	{ pak[2] = YYCURSOR[-1] + 0x10; GOTO(get_clef); }
yy116:	yych = *++YYCURSOR;
	if(yych == 'd')	goto yy136;
	goto yy24;
yy117:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy118;
yy118:	if(yych <= ' '){
		if(yych <= '\f'){
			if(yych <= '\b')	goto yy24;
			if(yych <= '\n')	goto yy117;
			goto yy24;
		} else {
			if(yych <= '\r')	goto yy117;
			if(yych <= '\037')	goto yy24;
			goto yy117;
		}
	} else {
		if(yych <= '@'){
			if(yych != '=')	goto yy24;
			goto yy119;
		} else {
			if(yych <= 'G')	goto yy121;
			if(yych <= '`')	goto yy24;
			if(yych <= 'g')	goto yy121;
			goto yy24;
		}
	}
yy119:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy120;
yy120:	if(yych <= '\037'){
		if(yych <= '\n'){
			if(yych <= '\b')	goto yy24;
			goto yy119;
		} else {
			if(yych == '\r')	goto yy119;
			goto yy24;
		}
	} else {
		if(yych <= 'G'){
			if(yych <= ' ')	goto yy119;
			if(yych <= '@')	goto yy24;
			goto yy121;
		} else {
			if(yych <= '`')	goto yy24;
			if(yych >= 'h')	goto yy24;
			goto yy121;
		}
	}
yy121:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy122;
yy122:	if(yych == '\'')	goto yy121;
	if(yych == ',')	goto yy121;
	goto yy123;
yy123:
#line 260
	{ d=1; m=0;
                             YYSTART=YYCURSOR;
                             while (!isalpha(*(--YYSTART))) {
                               switch (*YYSTART) {
                                 case '\'': m++; break;
                                 case ',' : m--; break;
                               }
                             }
                             if (*YYSTART < 'C') m += 3;
                             else if (*YYSTART < 'c') m += 4;
                             else m+=5;
                             if (m<0) m=0; if (m>9) m=9;
                             pak[7]=toupper(*YYSTART);
                             pak[8]='0'+m;
                             GOTO(get_clef);
                           }
yy124:	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != 'z')	goto yy122;
	goto yy125;
yy125:	yych = *++YYCURSOR;
	if(yych != 'z')	goto yy24;
	goto yy126;
yy126:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy24;
	goto yy127;
yy127:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 's')	goto yy129;
	goto yy128;
yy128:
#line 205
	{ pak[2] = 0x52; GOTO(get_clef); }
yy129:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy24;
	goto yy130;
yy130:	yych = *++YYCURSOR;
	if(yych != 'p')	goto yy24;
	goto yy131;
yy131:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy24;
	goto yy132;
yy132:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy24;
	goto yy133;
yy133:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy24;
	goto yy134;
yy134:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy24;
	goto yy135;
yy135:	yych = *++YYCURSOR;
	goto yy128;
yy136:	yych = *++YYCURSOR;
	if(yych != 'd')	goto yy24;
	goto yy137;
yy137:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy24;
	goto yy138;
yy138:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy117;
	goto yy24;
yy139:	yych = *++YYCURSOR;
	if(yych == 'o')	goto yy177;
	goto yy24;
yy140:	yych = *++YYCURSOR;
	if(yych == 'm')	goto yy172;
	goto yy24;
yy141:	yych = *++YYCURSOR;
	if(yych == 'b')	goto yy163;
	goto yy24;
yy142:	yych = *++YYCURSOR;
	if(yych == 'a')	goto yy156;
	if(yych == 'e')	goto yy26;
	goto yy24;
yy143:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy144;
yy144:	if(yych <= '\037'){
		if(yych <= '\n'){
			if(yych <= '\b')	goto yy24;
			goto yy143;
		} else {
			if(yych == '\r')	goto yy143;
			goto yy24;
		}
	} else {
		if(yych <= '9'){
			if(yych <= ' ')	goto yy143;
			if(yych <= '/')	goto yy24;
			goto yy147;
		} else {
			if(yych != '=')	goto yy24;
			goto yy145;
		}
	}
yy145:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy146;
yy146:	if(yych <= '\r'){
		if(yych <= '\b')	goto yy24;
		if(yych <= '\n')	goto yy145;
		if(yych <= '\f')	goto yy24;
		goto yy145;
	} else {
		if(yych <= ' '){
			if(yych <= '\037')	goto yy24;
			goto yy145;
		} else {
			if(yych <= '/')	goto yy24;
			if(yych >= ':')	goto yy24;
			goto yy147;
		}
	}
yy147:	yych = *++YYCURSOR;
	goto yy148;
yy148:
#line 257
	{ pak[6]=YYCURSOR[-1]; GOTO(get_clef); }
yy149:	yych = *++YYCURSOR;
	if(yych != 'p')	goto yy24;
	goto yy150;
yy150:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy24;
	goto yy151;
yy151:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy24;
	goto yy152;
yy152:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy24;
	goto yy153;
yy153:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy24;
	goto yy154;
yy154:	yych = *++YYCURSOR;
	goto yy155;
yy155:
#line 204
	{ pak[2] = 0x51; GOTO(get_clef); }
yy156:	yych = *++YYCURSOR;
	if(yych != 'f')	goto yy24;
	goto yy157;
yy157:	yych = *++YYCURSOR;
	if(yych != 'f')	goto yy24;
	goto yy158;
yy158:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy24;
	goto yy159;
yy159:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy24;
	goto yy160;
yy160:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy24;
	goto yy161;
yy161:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy24;
	goto yy162;
yy162:	yych = *++YYCURSOR;
	if(yych == 's')	goto yy143;
	goto yy24;
yy163:	yych = *++YYCURSOR;
	if(yych == 'b')	goto yy165;
	if(yych != 'n')	goto yy24;
	goto yy164;
yy164:	yych = *++YYCURSOR;
	if(yych == 'a')	goto yy170;
	goto yy24;
yy165:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy24;
	goto yy166;
yy166:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy24;
	goto yy167;
yy167:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy24;
	goto yy168;
yy168:	yych = *++YYCURSOR;
	goto yy169;
yy169:
#line 208
	{ pak[2] = 0x65; GOTO(get_clef); }
yy170:	yych = *++YYCURSOR;
	if(yych != 'm')	goto yy24;
	goto yy171;
yy171:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy24;
	goto yy172;
yy172:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy173;
yy173:	if(yych <= '\r'){
		if(yych <= '\b')	goto yy24;
		if(yych <= '\n')	goto yy172;
		if(yych <= '\f')	goto yy24;
		goto yy172;
	} else {
		if(yych <= ' '){
			if(yych <= '\037')	goto yy24;
			goto yy172;
		} else {
			if(yych != '=')	goto yy24;
			goto yy174;
		}
	}
yy174:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy175;
yy175:	if(yych <= '\f'){
		if(yych <= '\b')	goto yy176;
		if(yych <= '\n')	goto yy174;
		goto yy176;
	} else {
		if(yych <= '\r')	goto yy174;
		if(yych == ' ')	goto yy174;
		goto yy176;
	}
yy176:
#line 289
	{ d=14; GOTO(get_name); }
yy177:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy24;
	goto yy178;
yy178:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy24;
	goto yy179;
yy179:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy24;
	goto yy180;
yy180:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy24;
	goto yy181;
yy181:	yych = *++YYCURSOR;
	if(yych != 'm')	goto yy24;
	goto yy182;
yy182:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy172;
	goto yy24;
yy183:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy24;
	goto yy184;
yy184:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy24;
	goto yy185;
yy185:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy24;
	goto yy186;
yy186:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy24;
	goto yy187;
yy187:	yych = *++YYCURSOR;
	goto yy188;
yy188:
#line 203
	{ pak[2] = 0x42; GOTO(get_clef); }
yy189:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy24;
	goto yy190;
yy190:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy24;
	goto yy191;
yy191:	yych = *++YYCURSOR;
	if(yych != 'c')	goto yy24;
	goto yy192;
yy192:	yych = *++YYCURSOR;
	if(yych != 'h')	goto yy24;
	goto yy193;
yy193:	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'v')	goto yy195;
	goto yy194;
yy194:
#line 202
	{ pak[2] = 0x41; GOTO(get_clef); }
yy195:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy24;
	goto yy196;
yy196:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy24;
	goto yy197;
yy197:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy24;
	goto yy198;
yy198:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy24;
	goto yy199;
yy199:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy24;
	goto yy200;
yy200:	yych = *++YYCURSOR;
	goto yy194;
yy201:	yych = *++YYCURSOR;
	if(yych == 'h')	goto yy66;
	goto yy24;
yy202:	yych = *++YYCURSOR;
	if(yych != 'u')	goto yy24;
	goto yy203;
yy203:	yych = *++YYCURSOR;
	if(yych != 'm')	goto yy24;
	goto yy204;
yy204:	yych = *++YYCURSOR;
	goto yy205;
yy205:
#line 201
	{ pak[2] = 0x4F; GOTO(get_clef); }
yy206:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy24;
	goto yy207;
yy207:	yych = *++YYCURSOR;
	if(yych == 'c')	goto yy204;
	goto yy24;
yy208:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy209;
yy209:	if(yych <= '\r'){
		if(yych <= '\b')	goto yy210;
		if(yych <= '\n')	goto yy208;
		if(yych >= '\r')	goto yy208;
		goto yy210;
	} else {
		if(yych <= ' '){
			if(yych >= ' ')	goto yy208;
			goto yy210;
		} else {
			if(yych == '=')	goto yy217;
			goto yy210;
		}
	}
yy210:
#line 286
	{ d=10; GOTO(get_name); }
yy211:	yych = *++YYCURSOR;
	if(yych == 'm')	goto yy216;
	goto yy24;
yy212:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy24;
	goto yy213;
yy213:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy24;
	goto yy214;
yy214:	yych = *++YYCURSOR;
	goto yy215;
yy215:
#line 200
	{ pak[2] = 0x40; GOTO(get_clef); }
yy216:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy208;
	goto yy24;
yy217:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy218;
yy218:	if(yych <= '\f'){
		if(yych <= '\b')	goto yy210;
		if(yych <= '\n')	goto yy217;
		goto yy210;
	} else {
		if(yych <= '\r')	goto yy217;
		if(yych == ' ')	goto yy217;
		goto yy210;
	}
yy219:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy24;
	goto yy220;
yy220:	yych = *++YYCURSOR;
	if(yych != 'f')	goto yy24;
	goto yy221;
yy221:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy222;
yy222:	if(yych <= '\r'){
		if(yych <= '\b')	goto yy223;
		if(yych <= '\n')	goto yy221;
		if(yych >= '\r')	goto yy221;
		goto yy223;
	} else {
		if(yych <= ' '){
			if(yych >= ' ')	goto yy221;
			goto yy223;
		} else {
			if(yych == '=')	goto yy224;
			goto yy223;
		}
	}
yy223:
#line 186
	{ if (!isalpha(YYCURSOR[1])) {
                               pak[2] = 0x3A;
                               switch (*YYCURSOR) {
                                 case 'F': pak[2] += 0x10;
                                 case 'C': pak[2] += 0x10;
                                 case 'G': pak[2] += 0x10;
                                           YYCURSOR++;
                                           break;
                                 default: pak[2]=' ';
                               }
                             }
                             GOTO(get_clef);
                           }
yy224:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy225;
yy225:	if(yych <= '\f'){
		if(yych <= '\b')	goto yy223;
		if(yych <= '\n')	goto yy224;
		goto yy223;
	} else {
		if(yych <= '\r')	goto yy224;
		if(yych == ' ')	goto yy224;
		goto yy223;
	}
}
#line 296

  }     

  STATE(get_name) {
    c=*YYCURSOR;
    if (c == '\'' || c == '"') YYCURSOR++;
    else c=' '; 
    sethex(pak+d,off+((char *)YYCURSOR-str));
    m=0;
    while (m<256 && *YYCURSOR && *YYCURSOR != c) {
      m++; *YYCURSOR++;
      if (*YYCURSOR && YYCURSOR[-1] == '\\') {
        m++; *YYCURSOR++;
      }
    }
    sethex(pak+d+2,m);
    while (*YYCURSOR && *YYCURSOR == c) YYCURSOR++;
    GOTO(get_clef);
  }
   
  STATE(done)
    return pak;
}


static char abcpkdnote(char p, char a)
{
  p = (p-1) & 0x07;
  
  switch(a) {
    case 'S': return ('Q' + p);
    case 's': return ('q' + p);
    case 'F': return ('I' + p);
    case 'f': return ('i' + p);
    case 'N': return ('A' + p);
    default : return ('a' + p);
  }
}


char *abcNKey(char *pak, char *str)
{
  char t;
  int m=0, d=1;
  YYCTYPE *YYCURSOR,*YYLIMIT,*YYMARKER,*YYSTART;

  if (str==NULL || pak==NULL) return NULL;
  
  YYCURSOR=str; skipspace(YYCURSOR);
  YYLIMIT=str;  while (*YYLIMIT) YYLIMIT++;

  
             /*01234567890123456789012345678*/
  setpack(pak,"KETMabcdefgCENOTTSMMDNNnnSSss");
  
  if (! *YYCURSOR) GOTO(done);
  
  /* .{ Get the Tonic */
  YYSTART=YYCURSOR;
  
  {
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy226;
yy227:	++YYCURSOR;
yy226:
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	if(yych <= 'N'){
		if(yych <= 'G'){
			if(yych <= '\000')	goto yy228;
			if(yych <= '@')	goto yy235;
			goto yy229;
		} else {
			if(yych <= 'H')	goto yy231;
			if(yych <= 'M')	goto yy235;
			goto yy234;
		}
	} else {
		if(yych <= 'h'){
			if(yych <= '`')	goto yy235;
			if(yych <= 'g')	goto yy229;
			goto yy233;
		} else {
			if(yych == 'n')	goto yy234;
			goto yy235;
		}
	}
yy228:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy232;
	}
yy229:	yych = *++YYCURSOR;
	if(yych == '#')	goto yy244;
	if(yych == 'b')	goto yy244;
	goto yy230;
yy230:
#line 357
	{ t='n';
                  if ((YYCURSOR - YYSTART) > 1) 
                    t = (YYSTART[1] == '#')? 's': 'f';
                  pak[2] = abcpkdnote(*YYSTART,t);
                  GOTO(mode);
                }
yy231:	yych = *++YYCURSOR;
	if(yych == 'P')	goto yy242;
	if(yych == 'p')	goto yy240;
	goto yy232;
yy232:
#line 367
	{ YYCURSOR--  ; GOTO(mode); }
yy233:	yych = *++YYCURSOR;
	if(yych == 'p')	goto yy240;
	goto yy232;
yy234:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'O')	goto yy236;
	if(yych == 'o')	goto yy236;
	goto yy232;
yy235:	yych = *++YYCURSOR;
	goto yy232;
yy236:	yych = *++YYCURSOR;
	if(yych == 'N')	goto yy237;
	if(yych != 'n')	goto yy228;
	goto yy237;
yy237:	yych = *++YYCURSOR;
	if(yych == 'E')	goto yy238;
	if(yych != 'e')	goto yy228;
	goto yy238;
yy238:	yych = *++YYCURSOR;
	goto yy239;
yy239:
#line 365
	{ pak[2] = 'Z'; GOTO(mode); }
yy240:	yych = *++YYCURSOR;
	goto yy241;
yy241:
#line 364
	{ pak[2] = 'p'; GOTO(mode); }
yy242:	yych = *++YYCURSOR;
	goto yy243;
yy243:
#line 363
	{ pak[2] = 'P'; GOTO(mode); }
yy244:	yych = *++YYCURSOR;
	goto yy230;
}
#line 368

  /* .} */
  
  /* .{ Get the mode */
  STATE(mode) {
    {
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy245;
yy246:	++YYCURSOR;
yy245:
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if(yych <= 'L'){
		if(yych <= '@'){
			if(yych <= '\f'){
				if(yych <= '\000')	goto yy260;
				if(yych <= '\b')	goto yy262;
				if(yych >= '\v')	goto yy262;
				goto yy247;
			} else {
				if(yych <= '\r')	goto yy247;
				if(yych != ' ')	goto yy262;
				goto yy247;
			}
		} else {
			if(yych <= 'E'){
				if(yych <= 'A')	goto yy258;
				if(yych <= 'C')	goto yy262;
				if(yych <= 'D')	goto yy253;
				goto yy259;
			} else {
				if(yych == 'I')	goto yy257;
				if(yych <= 'K')	goto yy262;
				goto yy256;
			}
		}
	} else {
		if(yych <= 'e'){
			if(yych <= '`'){
				if(yych <= 'M')	goto yy249;
				if(yych == 'P')	goto yy255;
				goto yy262;
			} else {
				if(yych <= 'a')	goto yy258;
				if(yych <= 'c')	goto yy262;
				if(yych <= 'd')	goto yy253;
				goto yy259;
			}
		} else {
			if(yych <= 'l'){
				if(yych == 'i')	goto yy257;
				if(yych <= 'k')	goto yy262;
				goto yy256;
			} else {
				if(yych <= 'm')	goto yy251;
				if(yych == 'p')	goto yy255;
				goto yy262;
			}
		}
	}
yy247:	yych = *++YYCURSOR;
	goto yy304;
yy248:
#line 374
	{ GOTO(mode); }
yy249:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 'I'){
		if(yych == 'A')	goto yy293;
		if(yych >= 'I')	goto yy292;
		goto yy250;
	} else {
		if(yych <= 'a'){
			if(yych >= 'a')	goto yy293;
			goto yy250;
		} else {
			if(yych == 'i')	goto yy292;
			goto yy250;
		}
	}
yy250:
#line 387
	{ pak[3]='M' ; GOTO(exp);}
yy251:	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 'I'){
		if(yych == 'A')	goto yy293;
		if(yych >= 'I')	goto yy292;
		goto yy252;
	} else {
		if(yych <= 'a'){
			if(yych >= 'a')	goto yy293;
			goto yy252;
		} else {
			if(yych == 'i')	goto yy292;
			goto yy252;
		}
	}
yy252:
#line 386
	{ pak[3]='m' ; GOTO(exp);}
yy253:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'O')	goto yy288;
	if(yych == 'o')	goto yy288;
	goto yy254;
yy254:
#line 389
	{ YYCURSOR-- ; GOTO(exp);}
yy255:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'H')	goto yy284;
	if(yych == 'h')	goto yy284;
	goto yy254;
yy256:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 'Y'){
		if(yych == 'O')	goto yy276;
		if(yych <= 'X')	goto yy254;
		goto yy277;
	} else {
		if(yych <= 'o'){
			if(yych <= 'n')	goto yy254;
			goto yy276;
		} else {
			if(yych == 'y')	goto yy277;
			goto yy254;
		}
	}
yy257:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'O')	goto yy272;
	if(yych == 'o')	goto yy272;
	goto yy254;
yy258:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'E')	goto yy268;
	if(yych == 'e')	goto yy268;
	goto yy254;
yy259:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'X')	goto yy263;
	if(yych == 'x')	goto yy263;
	goto yy254;
yy260:	yych = *++YYCURSOR;
	goto yy261;
yy261:
#line 388
	{ GOTO(done); }
yy262:	yych = *++YYCURSOR;
	goto yy254;
yy263:	yych = *++YYCURSOR;
	if(yych == 'P')	goto yy265;
	if(yych == 'p')	goto yy265;
	goto yy264;
yy264:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 1:	goto yy252;
	case 0:	goto yy250;
	case 2:	goto yy254;
	}
yy265:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy266;
yy266:	if(yych <= '\f'){
		if(yych <= '\000')	goto yy267;
		if(yych <= '\b')	goto yy265;
		if(yych >= '\v')	goto yy265;
		goto yy267;
	} else {
		if(yych <= '\r')	goto yy267;
		if(yych != ' ')	goto yy265;
		goto yy267;
	}
yy267:
#line 385
	{ pak[3]='E' ; GOTO(exp);}
yy268:	yych = *++YYCURSOR;
	if(yych == 'O')	goto yy269;
	if(yych != 'o')	goto yy264;
	goto yy269;
yy269:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy270;
yy270:	if(yych <= '\f'){
		if(yych <= '\000')	goto yy271;
		if(yych <= '\b')	goto yy269;
		if(yych >= '\v')	goto yy269;
		goto yy271;
	} else {
		if(yych <= '\r')	goto yy271;
		if(yych != ' ')	goto yy269;
		goto yy271;
	}
yy271:
#line 384
	{ pak[3]='A' ; GOTO(exp);}
yy272:	yych = *++YYCURSOR;
	if(yych == 'N')	goto yy273;
	if(yych != 'n')	goto yy264;
	goto yy273;
yy273:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy274;
yy274:	if(yych <= '\f'){
		if(yych <= '\000')	goto yy275;
		if(yych <= '\b')	goto yy273;
		if(yych >= '\v')	goto yy273;
		goto yy275;
	} else {
		if(yych <= '\r')	goto yy275;
		if(yych != ' ')	goto yy273;
		goto yy275;
	}
yy275:
#line 383
	{ pak[3]='I' ; GOTO(exp);}
yy276:	yych = *++YYCURSOR;
	if(yych == 'C')	goto yy281;
	if(yych == 'c')	goto yy281;
	goto yy264;
yy277:	yych = *++YYCURSOR;
	if(yych == 'D')	goto yy278;
	if(yych != 'd')	goto yy264;
	goto yy278;
yy278:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy279;
yy279:	if(yych <= '\f'){
		if(yych <= '\000')	goto yy280;
		if(yych <= '\b')	goto yy278;
		if(yych >= '\v')	goto yy278;
		goto yy280;
	} else {
		if(yych <= '\r')	goto yy280;
		if(yych != ' ')	goto yy278;
		goto yy280;
	}
yy280:
#line 381
	{ pak[3]='L' ; GOTO(exp);}
yy281:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy282;
yy282:	if(yych <= '\f'){
		if(yych <= '\000')	goto yy283;
		if(yych <= '\b')	goto yy281;
		if(yych >= '\v')	goto yy281;
		goto yy283;
	} else {
		if(yych <= '\r')	goto yy283;
		if(yych != ' ')	goto yy281;
		goto yy283;
	}
yy283:
#line 382
	{ pak[3]='l' ; GOTO(exp);}
yy284:	yych = *++YYCURSOR;
	if(yych == 'R')	goto yy285;
	if(yych != 'r')	goto yy264;
	goto yy285;
yy285:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy286;
yy286:	if(yych <= '\f'){
		if(yych <= '\000')	goto yy287;
		if(yych <= '\b')	goto yy285;
		if(yych >= '\v')	goto yy285;
		goto yy287;
	} else {
		if(yych <= '\r')	goto yy287;
		if(yych != ' ')	goto yy285;
		goto yy287;
	}
yy287:
#line 380
	{ pak[3]='P' ; GOTO(exp);}
yy288:	yych = *++YYCURSOR;
	if(yych == 'R')	goto yy289;
	if(yych != 'r')	goto yy264;
	goto yy289;
yy289:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy290;
yy290:	if(yych <= '\f'){
		if(yych <= '\000')	goto yy291;
		if(yych <= '\b')	goto yy289;
		if(yych >= '\v')	goto yy289;
		goto yy291;
	} else {
		if(yych <= '\r')	goto yy291;
		if(yych != ' ')	goto yy289;
		goto yy291;
	}
yy291:
#line 379
	{ pak[3]='D' ; GOTO(exp);}
yy292:	yych = *++YYCURSOR;
	if(yych <= 'X'){
		if(yych == 'N')	goto yy297;
		if(yych <= 'W')	goto yy264;
		goto yy300;
	} else {
		if(yych <= 'n'){
			if(yych <= 'm')	goto yy264;
			goto yy297;
		} else {
			if(yych == 'x')	goto yy300;
			goto yy264;
		}
	}
yy293:	yych = *++YYCURSOR;
	if(yych == 'J')	goto yy294;
	if(yych != 'j')	goto yy264;
	goto yy294;
yy294:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy295;
yy295:	if(yych <= '\f'){
		if(yych <= '\000')	goto yy296;
		if(yych <= '\b')	goto yy294;
		if(yych >= '\v')	goto yy294;
		goto yy296;
	} else {
		if(yych <= '\r')	goto yy296;
		if(yych != ' ')	goto yy294;
		goto yy296;
	}
yy296:
#line 376
	{ pak[3]='M' ; GOTO(exp);}
yy297:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy298;
yy298:	if(yych <= '\f'){
		if(yych <= '\000')	goto yy299;
		if(yych <= '\b')	goto yy297;
		if(yych >= '\v')	goto yy297;
		goto yy299;
	} else {
		if(yych <= '\r')	goto yy299;
		if(yych != ' ')	goto yy297;
		goto yy299;
	}
yy299:
#line 377
	{ pak[3]='m' ; GOTO(exp);}
yy300:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy301;
yy301:	if(yych <= '\f'){
		if(yych <= '\000')	goto yy302;
		if(yych <= '\b')	goto yy300;
		if(yych >= '\v')	goto yy300;
		goto yy302;
	} else {
		if(yych <= '\r')	goto yy302;
		if(yych != ' ')	goto yy300;
		goto yy302;
	}
yy302:
#line 378
	{ pak[3]='X' ; GOTO(exp);}
yy303:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy304;
yy304:	if(yych <= '\f'){
		if(yych <= '\b')	goto yy248;
		if(yych <= '\n')	goto yy303;
		goto yy248;
	} else {
		if(yych <= '\r')	goto yy303;
		if(yych == ' ')	goto yy303;
		goto yy248;
	}
}
#line 390

  }
  /* .} */
  
  /* .{ Get explicit accidentals in the key */
  
  STATE(exp) {
    YYSTART=YYCURSOR;
    
    {
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy305;
yy306:	++YYCURSOR;
yy305:
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if(yych <= '<'){
		if(yych <= '\f'){
			if(yych <= '\000')	goto yy314;
			if(yych <= '\b')	goto yy316;
			if(yych >= '\v')	goto yy316;
			goto yy307;
		} else {
			if(yych <= '\r')	goto yy307;
			if(yych != ' ')	goto yy316;
			goto yy307;
		}
	} else {
		if(yych <= ']'){
			if(yych <= '=')	goto yy312;
			if(yych <= '@')	goto yy316;
			if(yych <= 'G')	goto yy313;
			goto yy316;
		} else {
			if(yych <= '_'){
				if(yych <= '^')	goto yy309;
				goto yy311;
			} else {
				if(yych <= '`')	goto yy316;
				if(yych <= 'g')	goto yy313;
				goto yy316;
			}
		}
	}
yy307:	yych = *++YYCURSOR;
	goto yy341;
yy308:
#line 400
	{ GOTO(exp); }
yy309:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= ']'){
		if(yych <= '@')	goto yy310;
		if(yych <= 'G')	goto yy335;
		goto yy310;
	} else {
		if(yych <= '^')	goto yy337;
		if(yych <= '`')	goto yy310;
		if(yych <= 'g')	goto yy335;
		goto yy310;
	}
yy310:
#line 414
	{ YYCURSOR-- ; GOTO(clef);}
yy311:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '^'){
		if(yych <= '@')	goto yy310;
		if(yych <= 'G')	goto yy329;
		goto yy310;
	} else {
		if(yych <= '_')	goto yy331;
		if(yych <= '`')	goto yy310;
		if(yych <= 'g')	goto yy329;
		goto yy310;
	}
yy312:	yych = *++YYCURSOR;
	if(yych <= '@')	goto yy310;
	if(yych <= 'G')	goto yy327;
	if(yych <= '`')	goto yy310;
	if(yych <= 'g')	goto yy327;
	goto yy310;
yy313:	yych = *++YYCURSOR;
	if(yych <= '<'){
		if(yych == '#')	goto yy321;
		goto yy310;
	} else {
		if(yych <= '=')	goto yy317;
		if(yych == 'b')	goto yy319;
		goto yy310;
	}
yy314:	yych = *++YYCURSOR;
	goto yy315;
yy315:
#line 412
	{ GOTO(done); }
yy316:	yych = *++YYCURSOR;
	goto yy310;
yy317:	yych = *++YYCURSOR;
	goto yy318;
yy318:
#line 411
	{ pak[3 + (*YYSTART & 0x07)] = 'N'; GOTO(exp); }
yy319:	yych = *++YYCURSOR;
	if(yych == 'b')	goto yy325;
	goto yy320;
yy320:
#line 410
	{ pak[3 + (*YYSTART & 0x07)] = 'f'; GOTO(exp); }
yy321:	yych = *++YYCURSOR;
	if(yych == '#')	goto yy323;
	goto yy322;
yy322:
#line 408
	{ pak[3 + (*YYSTART & 0x07)] = 's'; GOTO(exp); }
yy323:	yych = *++YYCURSOR;
	goto yy324;
yy324:
#line 407
	{ pak[3 + (*YYSTART & 0x07)] = 'S'; GOTO(exp); }
yy325:	yych = *++YYCURSOR;
	goto yy326;
yy326:
#line 409
	{ pak[3 + (*YYSTART & 0x07)] = 'F'; GOTO(exp); }
yy327:	yych = *++YYCURSOR;
	goto yy328;
yy328:
#line 405
	{ pak[3 + (YYCURSOR[-1] & 0x07)] = 'N'; GOTO(exp); }
yy329:	yych = *++YYCURSOR;
	goto yy330;
yy330:
#line 404
	{ pak[3 + (YYCURSOR[-1] & 0x07)] = 'f'; GOTO(exp); }
yy331:	yych = *++YYCURSOR;
	if(yych <= '@')	goto yy332;
	if(yych <= 'G')	goto yy333;
	if(yych <= '`')	goto yy332;
	if(yych <= 'g')	goto yy333;
	goto yy332;
yy332:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy310;
	}
yy333:	yych = *++YYCURSOR;
	goto yy334;
yy334:
#line 403
	{ pak[3 + (YYCURSOR[-1] & 0x07)] = 'F'; GOTO(exp); }
yy335:	yych = *++YYCURSOR;
	goto yy336;
yy336:
#line 402
	{ pak[3 + (YYCURSOR[-1] & 0x07)] = 's'; GOTO(exp); }
yy337:	yych = *++YYCURSOR;
	if(yych <= '@')	goto yy332;
	if(yych <= 'G')	goto yy338;
	if(yych <= '`')	goto yy332;
	if(yych >= 'h')	goto yy332;
	goto yy338;
yy338:	yych = *++YYCURSOR;
	goto yy339;
yy339:
#line 401
	{ pak[3 + (YYCURSOR[-1] & 0x07)] = 'S'; GOTO(exp); }
yy340:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy341;
yy341:	if(yych <= '\f'){
		if(yych <= '\b')	goto yy308;
		if(yych <= '\n')	goto yy340;
		goto yy308;
	} else {
		if(yych <= '\r')	goto yy340;
		if(yych == ' ')	goto yy340;
		goto yy308;
	}
}
#line 415

  }
  /* .} */

  STATE(clef)
    clef(pak+11,YYCURSOR,(char *)YYCURSOR-str);
  
  STATE(done)
    return pak;
}   


/*
Voice
  012345678890123456789012
  VEIIiiCENOTTSMMDNNnnSSss
    \ \
     \ \_________________ ID length 
      \__________________ ID offset  

*/

char *abcNVoice(char *pak, char *str)
{
  char *t;
  int m=0, d=1;
  YYCTYPE *YYCURSOR,*YYLIMIT,*YYMARKER,*YYSTART;

  if (str==NULL || pak==NULL) return NULL;
  
  YYCURSOR=str; skipspace(YYCURSOR);
  YYLIMIT=str;  while (*YYLIMIT) YYLIMIT++;
  
             /*012345678901234567890123*/
  setpack(pak,"VEIIiiCENOTTSMMDNNnnSSss");
  
  sethex(pak+2,(char *)YYCURSOR-str);
  YYSTART=YYCURSOR;   
  
  while (m<65 && *YYCURSOR && !isspace(*YYCURSOR)) {
    m++;
    YYCURSOR++;
  }
  sethex(pak+4,YYCURSOR-YYSTART);
  
  while (*YYCURSOR && !isspace(*YYCURSOR)) YYCURSOR++;
  
  if (*YYCURSOR)
    clef(pak+6,YYCURSOR,(char *)YYCURSOR-str);
  
  return pak;
}   


/*
           
 0123456
 LENNDDS
   \ \ \__ Specified as string
    \ \___ denominamtor
     \____ Numerator   
     
 L: <num/den>
 0 doublewhole
 1 whole
 2 half
 3 quarter 
 4 eighth 
 5 sixteenth 
 6 thirtysecond 
 7 sixtyfourth 
 8 onetwentyeighth
 
*/


char *abcNLength(char *pak, char *str)
{
  char *t;char c;
  int m=0, d=1,n=1;
  YYCTYPE *YYCURSOR,*YYLIMIT,*YYMARKER,*YYSTART;

  if (str==NULL || pak==NULL) return NULL;
  
  YYCURSOR=str; skipspace(YYCURSOR);
  
               /*012345678901234567890123*/
  setpack(pak,"LENNDDS");
  
  m=getfrac(&YYCURSOR,&n,&d);


  if (m >1 ) 
    setperr(pak,m);
  else {
    sethex(pak+2,n);
    sethex(pak+4,d);     
  }
  return pak;
}

